osd-level=0

sub-blur=10
sub-bold=yes
sub-border-color='#151515'
sub-border-size=2
sub-color='#ebebeb'
sub-font-size=40
sub-font=Source Code Pro
sub-margin-x=22
sub-margin-y=22
sub-scale-with-window=no
sub-use-margins=no
