#!/bin/sh

SLEEP_TIMEOUT=1800

$HOME/.fehbg
pgrep -x fcitx5 > /dev/null || fcitx5 &
pgrep -x picom > /dev/null || picom &
pgrep -x sxhkd > /dev/null || sxhkd &
pkill polybar
polybar &
xrdb -merge $HOME/.Xresources
xset dpms $SLEEP_TIMEOUT $SLEEP_TIMEOUT $SLEEP_TIMEOUT
xset r rate 300 50
xset s $SLEEP_TIMEOUT $SLEEP_TIMEOUT
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2

bspc config focused_border_color `xrdb -get color7`
bspc config normal_border_color `xrdb -get color0`
bspc config presel_feedback_color `xrdb -get color7`

bspc config border_width 4
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config split_ratio 0.5
bspc config window_gap 20
